[package]
name = "dif"
version = "0.1.0"
description = "Device Information File, a library for reading .dif files into a Rust struct."

[workspace]
members = [
    "tests/",
]

[dev-dependencies]
tests = { path = "tests/" }

[features]
alloc = []
